### ISSUE TITLE
Maybe pull in the f-spot lcms code?

### ISSUE THREAD

**Issue by decriptor** [jrshoare/lcmsNET#1]
It'd be nice to use your library instead of keeping lcms code around in https://github.com/f-spot/f-spot. Maybe there is some useful stuff in the f-spot that could benefit your library?

f-spot's lcms code: https://github.com/f-spot/f-spot/tree/master/src/Core/FSpot/Cms
https://github.com/f-spot/f-spot/blob/master/lib/libfspot/f-screen-utils.c

**Comment by jrshoare** [comment]
I have no issue with you using this library within the f-spot library. Not sure how you would go about including the sources, or perhaps you could pickup the NuGet package as part of your build.
The code is simply a wrapper around the lcms library as appears to be the case in your project.
It would mean some work to change some method signatures etc. of course.

**Comment by decriptor** [comment]
Sorry, I was thinking about using your lcmsNET NuGet in f-spot and replacing my lcms code in f-spot. I was wondering if you could take and use the code from f-spot to improve your library.

**Comment by jrshoare** [comment]
Always happy to accept suggestions to improve or fix bugs. Is there anything that is missing that f-spot needs? I have tried to maintain as a wrapper rather than add features to lcms but there may be something that I overlooked. For example, there is no support for plug-ins (yet?) although in a commercial project that uses lcmsNET I have included a plug-in to read/write a private tag.

**Comment by jrshoare** [comment]
I have added a couple of static methods to convert between CIEXYZ and CIExyY, and object methods for other conversions as per f-spot.

**Comment by decriptor** [comment]
Thanks. As soon as I get some time I'll look at converting over to your library.
