### ISSUE TITLE
 Failed to create instance of type 'lcmsNET.Profile'

### ISSUE THREAD

**Issue by jetic83** [jrshoare/lcmsNET#6]
I try to use this library for ICC profiles. Most of the time, it works very well, but occasionally, for the same image, it fails to create `Profile` instance.

I use a `ICCfile.icc` file, from which I create multiple `Profile `instances in my webapp. This is already failing occasionally.

I tested this with following code:

```
Profile[] profiles = new Profile[1000];
for (int i=0; i<1000; i++)
{
    try
    {
        profiles[i] = Profile.Open("ICCfile.icc", "r");
    } catch (Exception  e)
    {
        Console.WriteLine(e.Message);
    }
}
```

When running this multiple times, if throws an exception at i=509 (always). Is this a sort of restriction, maybe from memory? The .icc file is 12.5MB in size.

**Comment by jetic83** [comment]
Btw, it runs perfectly fine with this code:

```
Profile[] profiles = new Profile[1000];
for (int i=0; i<1000; i++)
{
    try
    {
        byte[] f = File.ReadAllBytes("ICCfile.icc");
        profiles[i] = Profile.Open(f);
    } catch (Exception  e)
    {
        Console.WriteLine(e.Message);
    }
}
```

**Comment by jrshoare** [comment]
The problem is with the underlying Little CMS implementation. I debugged into the code and found that in `cmsOpenIOhandlerFromFile(cmsContext, const char *, const char *)` in cmsio0.c that it fails to open the file for `case 'r':` when calling `fopen(FileName, mode)`.

Best guess is that you are reaching the limit on the number of simultaneous files that can be opened.

The Little CMS documentation states that the library allows you to close the profiles after creating a transform, so if you are doing this then maybe you don't need to keep the profiles open any longer than is needed to do this. That should help to prevent reaching the limit on file handles in use by `fopen`.

You can close the profile by calling `Close()` on the instance or by explicitly (or implicitly) disposing it.
